Fix type errors
When running the `Fraction` class in strict-type-checking mode the
following errors are thrown at runtime:

```
TypeError: rtrim() expects parameter 2 to be string, integer given
```

```
TypeError: str_pad() expects parameter 3 to be string, integer give
```

This diff changes those ints to strings so that the conversion doesn't
happen implicitly.